### ISSUE TITLE
summary based on findings...

### ISSUE THREAD

**Issue by sirvon** [ersin-ertan/android-multithreading#1]
Hey thanks for all your evaluations...

I follow you specifically because you put alot of diff android techniques to test..

It would be dope if you wrote like a few sentence summary of the pros/cons of each
technique/library you eval...

but anyhow thanks for your repos!

**Comment by ersin-ertan** [comment]
Hey Sirvon, I agree that a write up should be warranted, but not necessarily in pro/con format. Keep in mind that although it is open source, the repos are personally directed, thus the level of quality you may expect might not be there. 

That said I am planning on constructing documentation in a more organized way, both for myself and such community.
